name: Deploy Website CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        if [ -z "${{ secrets.SERVER_IP }}" ]; then
          echo "SERVER_IP is empty!"
          exit 1
        fi

        if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "SSH_PRIVATE_KEY is empty!"
          exit 1
        fi

        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -p 8022 -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        rsync -avz --delete \
        -e "ssh -p 8022 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
        ./ \
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_PATH }}